export const features = [
  { id: 'godot', orbit: 'inner', angle: 0 },
  { id: 'scene', orbit: 'inner', angle: 72 },
  { id: 'diagnostics', orbit: 'inner', angle: 144 },
  { id: 'worktree', orbit: 'inner', angle: 216 },
  { id: 'runs', orbit: 'inner', angle: 288 },
  { id: 'search', orbit: 'outer', angle: 0 },
  { id: 'local', orbit: 'outer', angle: 45 },
  { id: 'undo', orbit: 'outer', angle: 90 },
  { id: 'approval', orbit: 'outer', angle: 135 },
  { id: 'mcp', orbit: 'outer', angle: 180 },
  { id: 'skills', orbit: 'outer', angle: 225 },
  { id: 'computer', orbit: 'outer', angle: 270 },
  { id: 'providers', orbit: 'outer', angle: 315 },
];

export const content = {
  'zh-CN': {
    pageTitle: 'Daedalus Studio — 让想法，有方向',
    skip: '跳过动画，探索 Studio',
    explore: '探索',
    docs: '文档',
    languageButton: 'EN',
    languageLabel: 'Switch to English',
    featureLabel: 'Daedalus Studio 特性',
    progressLabel: '探索进度',
    scroll: '向下滚动，寻找方向',
    skipShort: '直达 Studio',
    download: '下载 Windows 版',
    start: '阅读入门文档',
    finalTitle: ['想法，准备就绪。', '现在，开始创造。'],
    finalBody: '从第一句想法，到有据可查的结果。你的下一个项目，从 Daedalus Studio 开始。',
    chapters: [
      {
        eyebrow: '01 / CONTEXT', title: ['先看懂，', '再行动。'],
        body: ['Godot 场景、脚本与编辑器状态，', '一次带入上下文。'],
        detailIndex: '01 — GODOT CONTEXT', detailTitle: '你的项目，不是空白对话。',
        detailBody: ['当前场景、选中节点、脚本和诊断，', '都成为这一次行动的上下文。'],
      },
      {
        eyebrow: '02 / FEATURES', title: ['把能力，', '放到轨道上。'],
        body: ['从项目上下文，到可控执行，', '每个能力都围绕你的工作运转。'],
      },
      {
        eyebrow: '03 / CONTROL', title: ['让它动手，', '由你决定。'],
        body: ['修改先变成可审阅的差异。', '写入、删除和命令，', '都经过明确审批。'],
        detailIndex: '03 — APPROVAL GATES', detailTitle: '自动化，不越过你的边界。',
        detailBody: ['读取、验证、提议、写入分级处理。', '每次改变都能看见，再决定。'],
        approval: '等待你的审阅',
      },
      {
        eyebrow: '04 / TRACE', title: ['任务结束，', '证据留下。'],
        body: ['终端输出、诊断、检查和变更，', '跟随任务一起保存。', '下次打开，直接接着真实状态继续。'],
        detailIndex: '04 — LOCAL TRACE', detailTitle: '不是一句「完成」，是一条记录。',
        detailBody: ['结果、警告与失败原因，', '都能在本地找回来。'],
        checks: ['代码检查', '终端输出', '任务记录'],
      },
    ],
    features: {
      godot: ['Godot 上下文', '场景、脚本与编辑器状态一并接入。'],
      scene: ['场景补丁', '把改动落成可审阅的最小差异。'],
      diagnostics: ['LSP 诊断', '先读懂错误，再给出可执行线索。'],
      worktree: ['工作树隔离', '在独立工作树试错，保持主线整洁。'],
      runs: ['任务恢复', '长任务随时暂停，回来继续执行。'],
      search: ['会话搜索', '跨任务找回决定、输出与上下文。'],
      local: ['本地优先', '项目与记录留在本机，状态可控。'],
      undo: ['撤销 / 重做', '每次修改都能回到上一个确定状态。'],
      approval: ['审批边界', '写入前先看差异，再决定是否放行。'],
      mcp: ['MCP', '连接外部工具，让工作流继续延伸。'],
      skills: ['Skills', '把重复流程封装成可复用能力。'],
      computer: ['Computer Use', '替你操作界面，关键步骤仍可见。'],
      providers: ['模型路由', '按任务选择合适模型，保持节奏。'],
    },
  },
  en: {
    pageTitle: 'Daedalus Studio — Give ideas a direction.',
    skip: 'Skip animation, explore Studio',
    explore: 'EXPLORE',
    docs: 'DOCS ↗',
    languageButton: '中文',
    languageLabel: '切换为中文',
    featureLabel: 'Daedalus Studio features',
    progressLabel: 'Explore progress',
    scroll: 'SCROLL TO FIND YOUR DIRECTION',
    skipShort: 'EXPLORE STUDIO ↗',
    download: 'DOWNLOAD FOR WINDOWS',
    start: 'READ THE DOCS ↗',
    finalTitle: ['Your idea is ready.', 'Make it real.'],
    finalBody: 'From the first idea to evidence you can inspect. Start your next project with Daedalus Studio.',
    chapters: [
      {
        eyebrow: '01 / CONTEXT', title: ['See it first.', 'Then act.'],
        body: ['Godot scene, script, and editor state.', 'One context for the work.'],
        detailIndex: '01 — GODOT CONTEXT', detailTitle: 'Your project is not a blank chat.',
        detailBody: ['The open scene, selected node, scripts, and diagnostics', 'become context for the work.'],
      },
      {
        eyebrow: '02 / FEATURES', title: ['Put every capability', 'in orbit.'],
        body: ['Context, tools, and guardrails', 'move together around your work.'],
      },
      {
        eyebrow: '03 / CONTROL', title: ['Let it act.', 'You decide.'],
        body: ['Changes arrive as reviewable diffs.', 'Writes, deletes, and commands', 'cross an explicit approval gate.'],
        detailIndex: '03 — APPROVAL GATES', detailTitle: 'Automation with a boundary.',
        detailBody: ['Read, verify, propose, and write are separate.', 'Every change stays visible before it lands.'],
        approval: 'READY FOR YOUR REVIEW',
      },
      {
        eyebrow: '04 / TRACE', title: ['The task ends.', 'The trace stays.'],
        body: ['Terminal output, diagnostics, checks, and changes', 'stay with the run.', 'Open it later. Continue from reality.'],
        detailIndex: '04 — LOCAL TRACE', detailTitle: 'Not “done”. A local trace.',
        detailBody: ['Results, warnings, and failure reasons', 'remain available when you need them.'],
        checks: ['Code checks', 'Terminal output', 'Task record'],
      },
    ],
    features: {
      godot: ['GODOT CONTEXT', 'Scene, scripts, and editor state arrive together.'],
      scene: ['SCENE PATCH', 'Turn each change into a reviewable minimal diff.'],
      diagnostics: ['LSP DIAGNOSTICS', 'Read the error first, then surface the next move.'],
      worktree: ['WORKTREE ISOLATION', 'Try ideas in an isolated tree while main stays clean.'],
      runs: ['DURABLE RUNS', 'Pause long tasks and pick them up where they left off.'],
      search: ['SESSION SEARCH', 'Find decisions, output, and context across every run.'],
      local: ['LOCAL FIRST', 'Projects and traces stay on your machine, under control.'],
      undo: ['UNDO / REDO', 'Return every edit to the last known good state.'],
      approval: ['APPROVAL GATES', 'See the diff before a write, then choose to let it through.'],
      mcp: ['MCP', 'Connect external tools and keep the workflow moving.'],
      skills: ['SKILLS', 'Package repeatable workflows into reusable capabilities.'],
      computer: ['COMPUTER USE', 'Let it operate the UI while every key step stays visible.'],
      providers: ['MODEL ROUTING', 'Choose the right model for the task and keep momentum.'],
    },
  },
};
